version: '3.8'
services:
  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: exchangeDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-app-network

volumes:
  postgres-data:

networks:
  spring-app-network:
    driver: bridge
